# -*- coding: utf-8 -*-
{
    'name': 'Support Service',
    'version': "1.0",
    'category': 'Support Service',
    'summary': 'Support Service management',
    'description': """This module provide support to the end users 
     and troubleshoot issues""",
    'author': "Cyllo",
    'company': "Cyllo",
    'maintainer': "Cyllo",
    'website': "https://www.cyllo.com",
    'depends': ['sale_management', 'hr_timesheet', 'cyllo_portal', 'cyllo_timer_widget', 'repair'],
    'data': [
        'security/support_service_ticket_security.xml',
        'security/ir.model.access.csv',
        'data/ir_cron_data.xml',
        'data/support_service_stage_data.xml',
        'reports/cyllo_support_service_reports.xml',
        'reports/support_service_ticket_templates.xml',
        'data/support_service_ticket_templates.xml',
        'views/support_service_overview_views.xml',
        'views/support_service_ticket_views.xml',
        'views/support_service_my_ticket_views.xml',
        'views/support_service_analysis_views.xml',
        'views/support_service_category_views.xml',
        'views/support_service_inactivity_views.xml',
        'views/support_service_tag_views.xml',
        'views/support_service_stage_views.xml',
        'views/support_service_team_views.xml',
        'views/support_service_portal_view.xml',
        'views/support_service_portal_templates.xml',
        'views/sale_order_view.xml',
        'views/cyllo_support_service_menu.xml',
        'wizards/account_move_reversal_views.xml',
        'wizards/repair_order_wizard_views.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
    'assets': {
        'web.assets_backend': [
            'cyllo_support_service/static/src/scss/support_service.scss',
            'cyllo_support_service/static/src/views/support_service_overview.xml',
            'cyllo_support_service/static/src/views/support_service_team_kanbanview.xml',
            'cyllo_support_service/static/src/js/support_service_overview.js',
            'cyllo_support_service/static/src/js/support_service_team_kanbanview.js',
            'cyllo_support_service/static/src/js/support_service_timer.js',
        ],
        'web.assets_frontend': [
            'cyllo_support_service/static/src/scss/support_service_portal.scss',
            'cyllo_support_service/static/src/js/portal_register_form.js',
        ],
    },
}
