# -*- coding: utf-8 -*-
{
    'name': 'Rental Management',
    'version': "1.0",
    'category': 'Rental',
    'summary': """This module is used to Rental Management.""",
    'description': "The Rental Management module in Cyllo is designed to streamline the process of managing rental "
                   "properties, equipment, or any other rental assets within your business",
    'author': "Cyllo",
    'company': "Cyllo",
    'maintainer': "Cyllo",
    'website': "https://www.cyllo.com",
    'depends': ['stock', 'account', 'website_sale', 'product', 'cyllo_portal', 'contacts'],
    'data': [
        'security/cyllo_rental_base_groups.xml',
        'security/ir.model.access.csv',
        'security/rental_order_security.xml',
        'data/ir_sequence_data.xml',
        'data/mail_data.xml',
        'data/stock_location_data.xml',
        'data/ir_cron_data.xml',
        'data/rental_menu_data.xml',
        'views/rental_order_views.xml',
        'views/product_product_views.xml',
        'views/stock_location_views.xml',
        'views/rental_contract_views.xml',
        'views/account_move_views.xml',
        'views/rental_templates.xml',
        'views/product_templates.xml',
        'views/payment_templates.xml',
        'views/rental_order_portal_templates.xml',
        'views/templates.xml',
        'views/rental_order_cart_templates.xml',
        'wizards/stock_picking_return_views.xml',
        'wizards/rental_delivery_views.xml',
        'reports/report_token_format.xml',
        'reports/rental_report_template.xml',
        'reports/rental_token_template.xml',
        'reports/report_rental_order.xml',
        'reports/report_rental_token.xml',
        'views/cyllo_rental_base_menus.xml',
        'views/rental_contract_template_views.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'cyllo_rental_base/static/src/js/rental_duration.js',
            'cyllo_rental_base/static/src/js/website_sale.js',
            'cyllo_rental_base/static/src/js/rental_portal.js',
            'cyllo_rental_base/static/src/css/website.css',
        ],
        'web.qunit_suite_tests': [
            'cyllo_rental_base/static/src/tests/rental_request_create_tests.js',
            'cyllo_rental_base/static/src/tests/rental_sale_tests.js',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'auto_install': False,
}
