# -*- coding: utf-8 -*-
{
    'name': 'Cyllo Payroll Management',
    'version': '1.0',
    'category': 'Human Resources ',
    'summary': """Used to manage the payroll module""",
    'description': """The module helps you to manage the employee contract, and payroll management in cyllo.""",
    'author': "Cyllo",
    'company': "Cyllo",
    'maintainer': "Cyllo",
    'website': "https://www.cyllo.com",
    'depends': ['hr_contract', 'mail', 'account', 'hr_work_entry', 'hr_attendance', 'hr_work_entry_contract',
                'hr_work_entry_holidays', 'contacts', 'hr_holidays'],
    'data': [
        'security/cyllo_payroll_management_groups.xml',
        'security/cyllo_payroll_management_rules.xml',
        'security/ir.model.access.csv',
        'reports/employee_resignation_request_report_templates.xml',
        'data/employee_salary_rule_category_data.xml',
        'data/account_journal_data.xml',
        'data/salary_structure_type_data.xml',
        'data/employee_salary_rule_data.xml',
        'data/employee_salary_structure_data.xml',
        'data/ir_sequence_data.xml',
        'data/ir_cron_data.xml',
        'data/decimal_precision_data.xml',
        'data/employee_payslip_other_input_data.xml',
        'data/mail_template_data.xml',
        'views/hr_contract_views.xml',
        'views/employee_salary_structure_views.xml',
        'views/salary_structure_type_views.xml',
        'views/employee_salary_rule_category_views.xml',
        'views/employee_salary_rule_views.xml',
        'views/employee_payslip_views.xml',
        'views/employee_payslip_batch_views.xml',
        'views/hr_employee_views.xml',
        'views/hr_work_entry_type_views.xml',
        'views/employee_resignation_views.xml',
        'views/resigned_reasons_views.xml',
        'views/gratuity_configuration_views.xml',
        'views/gratuity_settlement_views.xml',
        'views/employee_training_period_views.xml',
        'views/employee_payslip_other_input_views.xml',
        'views/employee_salary_attachment_views.xml',
        'views/account_move_views.xml',
        'wizards/resignation_request_confirm_views.xml',
        'wizards/employee_payslip_batch_list_views.xml',
        'reports/employee_payslip_report_templates.xml',
        'views/cyllo_payroll_management_menu_views.xml',
        'views/res_config_settings_views.xml',
        'views/res_company_views.xml',
    ],
    'license': "LGPL-3",
    'installable': True,
    'application': True,
    'auto_install': False,
}
