# -*- coding: utf-8 -*-
{
    'name': 'Cyllo Subscription',
    'version': '1.0.0',
    'author': "Cyllo",
    'company': "Cyllo",
    'maintainer': "Cyllo",
    "summary": """Allows the users to create and sell subscription products.""",
    'description': """This module helps to introduce and sell subscription products.""",
    'website': "https://www.cyllo.com",
    'depends': ['base', 'sale_management', 'portal'],
    'data': [
        'security/cyllo_subscription_security.xml',
        'security/ir.model.access.csv',
        'data/ir_cron_data.xml',
        'data/subscription_renew_templates.xml',
        'data/invoice_mail_templates.xml',
        'reports/subscription_report_views.xml',
        'views/account_move_views.xml',
        'views/product_template_views.xml',
        'views/sale_order_views.xml',
        'views/time_based_pricing_views.xml',
        'views/sale_order_template_views.xml',
        'views/subscription_order_views.xml',
        'views/subscription_portal_views.xml',
        'views/subscription_order_close_reason_views.xml',
        'views/susbcription_order_alert_views.xml',
        'wizards/subscription_close_views.xml',
        'views/cyllo_subscription_menus.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
