# -*- coding: utf-8 -*-
{
    'name': 'Cyllo Analytics',
    'version': '1.0',
    'category': 'Extra Tools',
    'summary': """This module helps businesses with the ability to transform raw data into actionable insights""",
    'description': 'Cyllo Dashboard is a robust module amplifying data analytics and reporting in Blue grail ERP. It '
                   'converts raw data into actionable insights, empowering informed decisions and strategic planning.',
    'author': 'Cyllo',
    'company': 'Cyllo',
    'maintainer': 'Cyllo',
    'website': 'https://www.cyllo.com',
    'license': 'LGPL-3',
    'depends': ['cyllo_base', 'web'],
    'data': [
        'security/dashboard_config_security.xml',
        'security/ir.model.access.csv',
        'data/banner/dashboard_banner.xml',
        'data/dashboard_sheet_type_data.xml',
        'data/dashboard_global_filter_data.xml',
        'data/theme/dashboard_theme_walden.xml',
        'data/theme/dashboard_theme_infographic.xml',
        'data/theme/dashboard_theme_roma.xml',
        'data/theme/dashboard_theme_chalk.xml',
        'data/theme/dashboard_theme_dark.xml',
        'data/theme/dashboard_theme_essos.xml',
        'data/theme/dashboard_theme_macarons.xml',
        'data/theme/dashboard_theme_vintage.xml',
        'data/theme/dashboard_theme_wonderland.xml',
        'data/theme/dashboard_theme_westeros.xml',
        'data/theme/dashboard_theme_purple_passion.xml',
        'data/theme/dashboard_theme_shine.xml',
        'data/sheet/dashboard_line_sheet_data.xml',
        'views/dashboard_config_views.xml',
        'views/dashboard_sheet.xml',
        'views/cyllo_dashboard_templates.xml',
        'views/res_config_settings_views.xml',
    ],
    'uninstall_hook': 'cyllo_d_uninstall_hook',
    'post_init_hook': 'cyllo_d_post_init_hook',
    "external_dependencies": {
        'python': ['openai']
    },
    'assets': {
        'web.assets_backend': [
            'cyllo_analytics/static/src/lib/codeMirror/*',
            'cyllo_analytics/static/src/lib/gridStack/*',
            'https://cdn.jsdelivr.net/npm/reveal.js@4.1.0/dist/reveal.js',
            'https://cdn.jsdelivr.net/npm/reveal.js@4.1.0/dist/reveal.css',
            'https://cdn.jsdelivr.net/npm/reveal.js@4.1.0/dist/theme/white.css',
            'https://unpkg.com/markdown-it@12.2.0/dist/markdown-it.min.js',
            'cyllo_analytics/static/src/lib/*',
            'cyllo_analytics/static/src/lib/eChart/*',
            'cyllo_analytics/static/src/css/*',
            'cyllo_analytics/static/src/views/tile/*',
            'cyllo_analytics/static/src/views/tile/components/*',
            'cyllo_analytics/static/src/views/tile/tile_searchbar/*',
            'cyllo_analytics/static/src/xml/cyllo_dashboard.xml',
            'cyllo_analytics/static/src/xml/configuration_dialog.xml',
            'cyllo_analytics/static/src/xml/menu_dialog_templates.xml',
            'cyllo_analytics/static/src/xml/delete_dialog_templates.xml',
            'cyllo_analytics/static/src/xml/editDashboard.xml',
            'cyllo_analytics/static/src/xml/presentationPreview.xml',
            'cyllo_analytics/static/src/xml/presentationMaker.xml',
            'cyllo_analytics/static/src/xml/CylloSheet.xml',
            'cyllo_analytics/static/src/xml/aiExplanation.xml',
            'cyllo_analytics/static/src/xml/import_dialog.xml',
            'cyllo_analytics/static/src/xml/DragNDrop.xml',
            'cyllo_analytics/static/src/xml/kpiSheet.xml',
            'cyllo_analytics/static/src/xml/filterDropdown.xml',
            'cyllo_analytics/static/src/xml/dashboardFilter.xml',
            'cyllo_analytics/static/src/js/cyllo_dashboard.js',
            'cyllo_analytics/static/src/js/query/query_manager.js',
            'cyllo_analytics/static/src/js/mixin/*',
            'cyllo_analytics/static/src/js/*',
            'cyllo_analytics/static/src/js/table/*',
            'cyllo_analytics/static/src/js/presentation/*',
            'cyllo_analytics/static/src/js/charts/*',
            'cyllo_analytics/static/src/js/explain_with_ai/components/*',
            'cyllo_analytics/static/src/js/explain_with_ai/*',
            'cyllo_analytics/static/src/js/presentation/components/*',
            'cyllo_analytics/static/src/js/sheet_filter/*',
            'cyllo_analytics/static/src/js/editor/*',
            'cyllo_analytics/static/src/js/fields/*',
            'cyllo_analytics/static/src/tests/tours/dashboard_onboarding.js',
        ],
        "web.qunit_suite_tests": [
            'cyllo_analytics/static/src/tests/*',
        ]
    },
    'images': [
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
