# -*- coding: utf-8 -*-
from . import account_move
from . import employee_salary_rule
from . import employee_payslip
from . import employee_payslip_batch
from . import employee_payslip_other_input
from . import employee_resignation
from . import employee_salary_attachment
from . import employee_salary_rule_category
from . import employee_salary_structure
from . import employee_training_period
from . import gratuity_configuration
from . import gratuity_settlement
from . import hr_contract
from . import hr_employee
from . import hr_leave
from . import hr_work_entry_type
from . import res_company
from . import res_config_settings
from . import resigned_reasons
from . import salary_structure_type
