# -*- coding: utf-8 -*-
{
    "name": "Spreadsheet",
    "version": "1.0",
    "category": "Extra Tools",
    "summary": """Allow to create & edit spreadsheets""",
    "description": "Allow to add data to spreadsheet and edit the spreadsheet",
    'author': "Cyllo",
    'company': "Cyllo",
    'maintainer': "Cyllo",
    'website': "https://www.cyllo.com",
    "depends": ["web", "spreadsheet", "base_sparse_field", "bus"],
    "data": [
        "security/cyllo_spreadsheet_security.xml",
        "security/ir.model.access.csv",
        "views/spreadsheet_spreadsheet_views.xml",
        "data/spreadsheet_spreadsheet_import_mode.xml",
        "wizards/spreadsheet_spreadsheet_import_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "cyllo_spreadsheet/static/src/spreadsheet/spreadsheet.scss",
            "cyllo_spreadsheet/static/src/spreadsheet/spreadsheet.xml",
            "cyllo_spreadsheet/static/src/spreadsheet/spreadsheet_action.js",
            "cyllo_spreadsheet/static/src/spreadsheet/pivot_renderer.js",
            "cyllo_spreadsheet/static/src/spreadsheet/graph_renderer.js",
            "cyllo_spreadsheet/static/src/spreadsheet/list_renderer.js",
            "cyllo_spreadsheet/static/src/spreadsheet/kanban_renderer.js",
            "cyllo_spreadsheet/static/src/add_spreadsheet_menu/cog_menu.js",
            "cyllo_spreadsheet/static/src/add_spreadsheet_menu/cog_menu.xml",
            "cyllo_spreadsheet/static/src/add_spreadsheet_menu/add_list_spreadsheet.js",
            "cyllo_spreadsheet/static/src/add_spreadsheet_menu/add_menu_spreadsheet.js",
            "cyllo_spreadsheet/static/src/css/style.css",
            "cyllo_spreadsheet/static/src/spreadsheet_action/deleteDialog.js",
            "cyllo_spreadsheet/static/src/spreadsheet_action/deleteDialog.xml",
            "cyllo_spreadsheet/static/src/spreadsheet_action/spreadsheet_view.js",
            "cyllo_spreadsheet/static/src/spreadsheet_action/spreadsheet_view.xml",
            "cyllo_spreadsheet/static/src/spreadsheet_action/shareDialog.xml",
            "cyllo_spreadsheet/static/src/spreadsheet_action/shareDialog.js",
            "cyllo_spreadsheet/static/src/spreadsheet_action/shareMultipleDialog.js",
            'cyllo_spreadsheet/static/src/lib/*',
        ],
        "spreadsheet.o_spreadsheet": [
            "cyllo_spreadsheet/static/src/spreadsheet/bundle/spreadsheet_controlpanel.js",
            "cyllo_spreadsheet/static/src/spreadsheet/bundle/spreadsheet.xml",
            "cyllo_spreadsheet/static/src/spreadsheet/bundle/icon.xml",
            "cyllo_spreadsheet/static/src/spreadsheet/bundle/spreadsheet_renderer.js",
            "cyllo_spreadsheet/static/src/spreadsheet/bundle/spreadsheet_action.js",
            "cyllo_spreadsheet/static/src/spreadsheet/bundle/spreadsheet_control_panel.js",
            "cyllo_spreadsheet/static/src/spreadsheet/bundle/spreadsheet_download_menus.js",
            "cyllo_spreadsheet/static/src/spreadsheet/bundle/odoo_panels.esm.js",
            "cyllo_spreadsheet/static/src/spreadsheet/bundle/filter.esm.js",
        ],
    },
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
