# -*- coding: utf-8 -*-
import re
from lxml import etree
import base64

from odoo.http import Controller, route, request


class StudioReportController(Controller):
    """
    A controller for Odoo Studio report, handling saving of modifications.
    """

    @staticmethod
    def _strip_studio_attrs(tree):
        """
        Walk every element in *tree* and remove all studio-injected
        attributes that must never appear in saved QWeb templates.
        This is the authoritative server-side cleanup that catches any
        attrs the browser cleanup may have missed.
        """
        REMOVE_ATTRS = {'cy-xpath', 'cy-template', 'cy-type', 'draggable'}
        for el in tree.iter():
            for attr in REMOVE_ATTRS:
                el.attrib.pop(attr, None)
            # Strip cursor / outline from inline style
            style = el.get('style', '')
            if style:
                props = [p.strip() for p in style.split(';') if p.strip()]
                clean = [p for p in props
                         if not p.lower().startswith('cursor')
                         and not p.lower().startswith('outline')]
                if clean:
                    el.set('style', '; '.join(clean) + ';')
                else:
                    el.attrib.pop('style', None)

    @route('/cyllo_studio/create/inherited_view', auth="user", csrf=False,
           type='json')
    def create_inherited_view(self, all_arch):
        """
        Create or update inherited QWeb views from the report editor.
        Each item in all_arch has:
          - key:        external ID of the base template
          - xpathBlocks: XML string with <data><xpath ...>...</xpath></data>
        """
        try:
            for arch in all_arch:
                key = arch['key']
                xpath_blocks = re.sub(r'<br\s*>', '<br/>', arch['xpathBlocks'])

                # Fix void HTML elements that XMLSerializer may not self-close
                for tag in ['img', 'input', 'hr', 'link', 'meta']:
                    xpath_blocks = re.sub(
                        rf'<{tag}([^>]*?)(?<!/)>',
                        rf'<{tag}\1/>',
                        xpath_blocks,
                    )
                    
                # Fix double-encoded JSON in t-options generated by JS DOM serialization
                # JS creates: t-options="{&quot;widget&quot;: &quot;contact&quot;}"
                # QWeb needs valid python dicts: t-options='{"widget": "contact"}'
                xpath_blocks = xpath_blocks.replace('&quot;', "'")

                # Restore <cy-qweb-t> placeholder tags back to real QWeb <t> tags.
                # The iframe renderer encodes <t> → <cy-qweb-t> so that lxml's HTML
                # parser doesn't strip them; the JS serializer sends them as-is.
                xpath_blocks = re.sub(r'<cy-qweb-t(\s|>|/)', r'<t\1', xpath_blocks)
                xpath_blocks = xpath_blocks.replace('</cy-qweb-t>', '</t>')

                # Parse and validate
                try:
                    arch_el = etree.fromstring(xpath_blocks.encode('utf-8'))
                except etree.XMLSyntaxError as xml_err:
                    return {'success': False,
                            'error': f'Invalid XML in changes: {xml_err}'}

                # ── Strip studio attrs from incoming content ─────────────────
                self._strip_studio_attrs(arch_el)

                custom_arch = request.env['ir.ui.view'].search(
                    [('name', '=', f'Custom_{key}')])

                if custom_arch:
                    root = etree.fromstring(custom_arch.arch_base.encode('utf-8'))
                    # Heal any previously saved corruption
                    self._strip_studio_attrs(root)
                    data_node = root.xpath('//data')[0]
                    existing_exprs = {el.get('expr') for el in root.xpath('//*[@expr]')}
                    for new_el in arch_el:
                        expr = new_el.get('expr')
                        if expr in existing_exprs:
                            for old_el in root.xpath(f'//*[@expr="{expr}"]'):
                                old_el.getparent().remove(old_el)
                        data_node.insert(0, new_el)
                    new_arch = etree.tostring(root, encoding='unicode',
                                              pretty_print=True)
                    custom_arch.write({'arch_base': new_arch})
                else:
                    # ── Create new inherited view ────────────────────────────
                    base_view = request.env.ref(key)
                    if not base_view.exists():
                        return {'success': False,
                                'error': f'Base view {key!r} not found'}
                    clean_arch = etree.tostring(arch_el, encoding='unicode',
                                                pretty_print=True)
                    request.env['ir.ui.view'].create({
                        'name': f'Custom_{key}',
                        'type': 'qweb',
                        'mode': 'extension',
                        'inherit_id': base_view.id,
                        'arch_base': clean_arch,
                    })

            return {'success': True}

        except Exception as e:
            return {'success': False, 'error': str(e)}


    @route('/cyllo_studio/get_arch', auth='user', csrf=False, type='json')
    def get_arch(self, template):
        """
        Re-fetch the rendered report arch for a given template name.
        Called by the frontend when arch is lost after a browser page refresh
        (ir.actions.client params are not persisted across refreshes).
        """
        try:
            view = request.env.ref(template)
            if not view.exists():
                return {'success': False, 'error': f'Template {template!r} not found'}
            arch = view.get_iframe_rendered_template(template)
            return {'success': True, 'arch': arch}
        except Exception as e:
            return {'success': False, 'error': str(e)}

    @route('/cyllo_studio/get_report_preview_data', auth='user', csrf=False, type='json')
    def get_report_preview_data(self, template, res_model):
        """
        Fetch records, report properties, and available paper formats for the preview sidebar.
        """
        try:
            report = request.env['ir.actions.report'].search([('report_name', '=', template)], limit=1)
            if not report:
                return {'success': False, 'error': f'Report {template!r} not found'}

            # Fetch recent records from the target model
            records = request.env[res_model].search([], limit=80)

            # Fetch available paper formats with dimensions
            paper_formats = request.env['report.paperformat'].search_read(
                [], ['id', 'name', 'page_width', 'page_height', 'format']
            )

            return {
                'success': True,
                'report': {
                    'id': report.id,
                    'name': report.name,
                    'report_name': report.report_name,
                    'model': report.model,
                    'paperformat_id': report.paperformat_id.id if report.paperformat_id else False,
                    'attachment_use': report.attachment_use,
                },
                'record_ids': records.ids,
                'paper_formats': paper_formats,
            }
        except Exception as e:
            return {'success': False, 'error': str(e)}

    @route('/cyllo_studio/render_report_html', auth='user', csrf=False, type='json')
    def render_report_html(self, report_id, doc_ids):
        """
        Render the target report with real data for the given doc_ids and return the HTML.
        """
        try:
            report = request.env['ir.actions.report'].browse(report_id)
            if not report.exists():
                return {'success': False, 'error': 'Report not found'}

            html_content, _ = report.sudo()._render_qweb_html(report.id, doc_ids)
            return {'success': True, 'html': html_content.decode('utf-8')}
        except Exception as e:
            return {'success': False, 'error': str(e)}

    @route('/cyllo_studio/get_report_source', auth='user', csrf=False, type='json')
    def get_report_source(self, template):
        """ Fetch the raw XML arch of the report template, preferring custom view. """
        try:
            # First look for a custom view
            custom_view = request.env['ir.ui.view'].search([('name', '=', f'Custom_{template}')], limit=1)
            if custom_view:
                return {'success': True, 'arch': custom_view.arch_base}

            # Fallback to base view
            view = request.env.ref(template, raise_if_not_found=False)
            if not view:
                # Try searching by name if ref fails (might just be the view name without module)
                view = request.env['ir.ui.view'].search([('name', '=', template)], limit=1)

            if not view.exists():
                return {'success': False, 'error': f'Template {template!r} not found'}
            return {'success': True, 'arch': view.arch_base}
        except Exception as e:
            return {'success': False, 'error': str(e)}

    @route('/cyllo_studio/save_report_source', auth='user', csrf=False, type='json')
    def save_report_source(self, template, arch):
        """ Save the raw XML arch directly to the inherited view (or create one). """
        try:
            custom_view = request.env['ir.ui.view'].search([('name', '=', f'Custom_{template}')], limit=1)
            if custom_view:
                custom_view.write({'arch_base': arch})
            else:
                base_view = request.env.ref(template)
                request.env['ir.ui.view'].create({
                    'name': f'Custom_{template}',
                    'type': 'qweb',
                    'mode': 'extension',
                    'inherit_id': base_view.id,
                    'arch_base': arch,
                })
            return {'success': True}
        except Exception as e:
            return {'success': False, 'error': str(e)}

