# -*- coding: utf-8 -*-
import re
from lxml import etree
import base64

from odoo.http import Controller, route, request
from odoo import fields
from datetime import timedelta


class StudioReportController(Controller):
    """
    A controller for Odoo Studio report, handling saving of modifications.
    """

    @staticmethod
    def _strip_studio_attrs(tree):
        """
        Walk every element in *tree* and remove all studio-injected
        attributes that must never appear in saved QWeb templates.
        This is the authoritative server-side cleanup that catches any
        attrs the browser cleanup may have missed.
        """
        REMOVE_ATTRS = {'cy-xpath', 'cy-template', 'cy-type', 'draggable'}
        for el in tree.iter():
            for attr in REMOVE_ATTRS:
                el.attrib.pop(attr, None)
            # Strip cursor / outline from inline style
            style = el.get('style', '')
            if style:
                props = [p.strip() for p in style.split(';') if p.strip()]
                clean = [p for p in props
                         if not p.lower().startswith('cursor')
                         and not p.lower().startswith('outline')]
                if clean:
                    el.set('style', '; '.join(clean) + ';')
                else:
                    el.attrib.pop('style', None)

    @route('/cyllo_studio/create/inherited_view', auth="user", csrf=False,
           type='json')
    def create_inherited_view(self, all_arch):
        """
        Create or update inherited QWeb views from the report editor.
        Each item in all_arch has:
          - key:        external ID of the base template
          - xpathBlocks: XML string with <data><xpath ...>...</xpath></data>
        """
        try:
            for arch in all_arch:
                key = arch['key']

                # Guard: never create/modify XPath overrides on protected layout templates.
                # These templates contain t-if/t-else sibling chains that QWeb requires to stay
                # adjacent; any inserted element breaks compilation with:
                #   SyntaxError: t-elif directive must be preceded by t-if or t-elif directive
                if key in self._PROTECTED_LAYOUT_KEYS:
                    print(f"[Cyllo Studio] Skipping protected layout template: {key}")
                    # Also clean up any accidentally created Custom_ views for this key
                    base_view = request.env.ref(key, raise_if_not_found=False)
                    if base_view:
                        stale = request.env['ir.ui.view'].sudo().search([
                            ('inherit_id', '=', base_view.id),
                            '|', ('name', 'like', 'Custom_'), ('key', 'like', 'Custom_'),
                        ])
                        if stale:
                            stale.unlink()
                    continue
                xpath_blocks = re.sub(r'<br\s*>', '<br/>', arch['xpathBlocks'])

                # Fix void HTML elements that XMLSerializer may not self-close
                for tag in ['img', 'input', 'hr', 'link', 'meta']:
                    xpath_blocks = re.sub(
                        rf'<{tag}([^>]*?)(?<!/)>',
                        rf'<{tag}\1/>',
                        xpath_blocks,
                    )

                # Fix double-encoded JSON in t-options generated by JS DOM serialization
                # JS creates: t-options="{&quot;widget&quot;: &quot;contact&quot;}"
                # QWeb needs valid python dicts: t-options='{"widget": "contact"}'
                # ONLY replace if it's inside a t-options block
                xpath_blocks = re.sub(r'(t-options\s*=\s*")([^"]*)(")',
                                      lambda m: m.group(1) + m.group(2).replace('&quot;', "'") + m.group(3),
                                      xpath_blocks)

                # Restore <cy-qweb-t> placeholder tags back to real QWeb <t> tags.
                # The iframe renderer encodes <t> → <cy-qweb-t> so that lxml's HTML
                # parser doesn't strip them; the JS serializer sends them as-is.
                xpath_blocks = re.sub(r'<cy-qweb-t(\s|>|/)', r'<t\1', xpath_blocks)
                xpath_blocks = xpath_blocks.replace('</cy-qweb-t>', '</t>')

                # Parse and validate
                try:
                    arch_el = etree.fromstring(xpath_blocks.encode('utf-8'))
                except etree.XMLSyntaxError as xml_err:
                    print(f"[Cyllo Studio] XML Syntax Error: {xml_err}\nBlocks: {xpath_blocks}")
                    return {'success': False,
                            'error': f'Invalid XML in changes: {xml_err}'}

                # ── Strip studio attrs from incoming content ─────────────────
                self._strip_studio_attrs(arch_el)

                print(f"[Cyllo Studio] Saving changes for {key}. XPaths: {[el.get('expr') for el in arch_el]}")

                # Search by KEY, which is much more reliable than name
                custom_arch = request.env['ir.ui.view'].search(
                    [('key', '=', f'Custom_{key}')])

                if custom_arch:
                    try:
                        root = etree.fromstring(custom_arch.arch_base.encode('utf-8'))
                        # Heal any previously saved corruption
                        self._strip_studio_attrs(root)

                        # ── Sync Model ───────────────────────────────────────
                        # Ensure the custom arch has the same model as the base
                        # view, otherwise Odoo's _get_combined_arch will skip it.
                        base_view = request.env.ref(key, raise_if_not_found=False)
                        if base_view and base_view.model and custom_arch.model != base_view.model:
                            custom_arch.write({'model': base_view.model})

                        data_nodes = root.xpath('//data')
                        if not data_nodes:
                            # If for some reason it's missing <data>, wrap it
                            new_root = etree.Element('data')
                            new_root.extend(list(root))
                            root = new_root
                            data_node = root
                        else:
                            data_node = data_nodes[0]

                        for new_el in arch_el:
                            expr = new_el.get('expr')
                            position = new_el.get('position')

                            # Purge logic:
                            for old_el in list(root.xpath('//*[@expr]')):
                                old_expr = old_el.get('expr', '')
                                
                                # 1. If we are REPLACING this exact node, remove the old replacement.
                                if position == 'replace' and old_expr == expr:
                                    p = old_el.getparent()
                                    if p is not None:
                                        p.remove(old_el)
                                
                                # 2. If we are modifying/replacing this node, any existing XPaths 
                                # that target its children are now stale/invalid.
                                elif old_expr.startswith(expr + '/'):
                                    p = old_el.getparent()
                                    if p is not None:
                                        p.remove(old_el)
                            
                            data_node.append(new_el)
                    except Exception as e:
                        print(f"[Cyllo Studio] Error merging into existing view: {e}")
                        # Fallback: just overwrite if merging fails
                        custom_arch.write({'arch_base': xpath_blocks})
                    new_arch = etree.tostring(root, encoding='unicode',
                                              pretty_print=True)
                    custom_arch.write({'arch_base': new_arch})
                else:
                    base_view = request.env.ref(key)
                    if not base_view.exists():
                        return {'success': False,
                                'error': f'Base view {key!r} not found'}
                    clean_arch = etree.tostring(arch_el, encoding='unicode',
                                                pretty_print=True)
                    request.env['ir.ui.view'].create({
                        'name': f'Custom_{key}',  # Name is descriptive
                        'key': f'Custom_{key}',  # Key is technical
                        'type': 'qweb',
                        'mode': 'extension',
                        'inherit_id': base_view.id,
                        'arch_base': clean_arch,
                        'model': base_view.model,  # Model is required for inheritance to work
                    })
            return {'success': True}

        except Exception as e:
            return {'success': False, 'error': str(e)}

    @route('/cyllo_studio/get_arch', auth='user', csrf=False, type='json')
    def get_arch(self, template, show_placeholders=True):
        """
        Re-fetch the rendered report arch for a given template name.
        Called by the frontend when arch is lost after a browser page refresh
        (ir.actions.client params are not persisted across refreshes).
        """
        try:
            view = request.env.ref(template)
            if not view.exists():
                return {'success': False, 'error': f'Template {template!r} not found'}
            
            try:
                arch = view.get_iframe_rendered_template(template, show_placeholders=show_placeholders)
                return {'success': True, 'arch': arch}
            except ValueError as ve:
                # If inheritance is broken, try to purge Custom_ views and retry once
                if "cannot be located in parent view" in str(ve):
                    print(f"[Cyllo Studio] Broken inheritance detected for {template}. Purging Custom_ views.")
                    custom_views = request.env['ir.ui.view'].search([
                        ('inherit_id', '=', view.id),
                        ('name', 'like', 'Custom_'),
                    ])
                    if custom_views:
                        custom_views.unlink()
                        # Retry once
                        arch = view.get_iframe_rendered_template(template, show_placeholders=show_placeholders)
                        return {'success': True, 'arch': arch}
                raise ve

        except Exception as e:
            return {'success': False, 'error': str(e)}

    @route('/cyllo_studio/get_report_preview_data', auth='user', csrf=False, type='json')
    def get_report_preview_data(self, template, res_model):
        """
        Fetch records, report properties, and available paper formats for the preview sidebar.
        """
        try:
            report = request.env['ir.actions.report'].search([('report_name', '=', template)], limit=1)
            if not report:
                return {'success': False, 'error': f'Report {template!r} not found'}

            # Fetch recent records from the target model
            records = request.env[res_model].search([], limit=80)

            # Fetch available paper formats with dimensions
            paper_formats = request.env['report.paperformat'].search_read(
                [], ['id', 'name', 'page_width', 'page_height', 'format']
            )

            return {
                'success': True,
                'report': {
                    'id': report.id,
                    'name': report.name,
                    'report_name': report.report_name,
                    'model': report.model,
                    'paperformat_id': report.paperformat_id.id if report.paperformat_id else False,
                    'attachment_use': report.attachment_use,
                },
                'record_ids': records.ids,
                'paper_formats': paper_formats,
            }
        except Exception as e:
            return {'success': False, 'error': str(e)}

    @route('/cyllo_studio/render_report_html', auth='user', csrf=False, type='json')
    def render_report_html(self, report_id, doc_ids):
        """
        Return a preview URL for the target report so the frontend can render it
        inside an <iframe src="..."> tag instead of using srcdoc with raw HTML.
        Using Odoo's native /report/html/ route ensures the report is fully styled
        (Odoo asset bundles load correctly) and all QWeb field values are resolved.
        """
        try:
            report = request.env['ir.actions.report'].browse(report_id)
            if not report.exists():
                return {'success': False, 'error': 'Report not found'}

            ids_str = ','.join(str(i) for i in doc_ids)
            preview_url = f'/report/html/{report.report_name}/{ids_str}'
            return {'success': True, 'preview_url': preview_url}
        except Exception as e:
            return {'success': False, 'error': str(e)}

    @route('/cyllo_studio/generate_qr_token', auth='user', type='json')
    def generate_qr_token(self, template, options):
        """
        Generate a reusable token for a report template.
        """
        try:
            report = request.env['ir.actions.report'].search([('report_name', '=', template)], limit=1)
            if not report:
                return {'success': False, 'error': 'Report not found'}

            token_vals = {
                'report_id': report.id,
                'require_auth': options.get('requireAuth', False),
                'track_analytics': options.get('trackAnalytics', True),
            }
            if options.get('expiresDays'):
                token_vals['expires_at'] = fields.Datetime.now() + timedelta(days=int(options['expiresDays']))

            token_record = request.env['qr.download.token'].create(token_vals)
            return {'success': True, 'token': token_record.token}
        except Exception as e:
            return {'success': False, 'error': str(e)}

    @route('/report/pdf/<int:report_id>/<int:record_id>', auth='public', methods=['GET'])
    def download_report_pdf(self, report_id, record_id, token=None, **kwargs):
        """
        Download the PDF for a specific report and record using a token.
        """
        if not token:
            return request.make_response("Missing token", status=403)

        token_record = request.env['qr.download.token'].sudo().search([
            ('token', '=', token),
            ('report_id', '=', report_id)
        ], limit=1)

        if not token_record or not token_record.is_valid():
            return request.make_response("Invalid or expired link", status=403)

        if token_record.require_auth and not request.session.uid:
            # Redirect to login if auth is required
            return request.redirect(f'/web/login?redirect=/report/pdf/{report_id}/{record_id}?token={token}')

        report = request.env['ir.actions.report'].sudo().browse(report_id)
        if not report.exists():
            return request.make_response("Report not found", status=404)

        # Track analytics
        if token_record.track_analytics:
            request.env['qr.scan.event'].sudo().create({
                'token_id': token_record.id,
                'record_id': record_id,
                'ip_address': request.httprequest.remote_addr,
                'user_agent': request.httprequest.user_agent.string,
            })
            token_record.sudo().scan_count += 1

        try:
            pdf_content, _ = report._render_qweb_pdf(report_id, [record_id])

            # Fetch record to build filename
            record = request.env[report.model].sudo().browse(record_id)
            doc_name = record.display_name.replace('/', '_') if record.exists() else str(record_id)
            filename = f"Report_{doc_name}.pdf"

            pdfhttpheaders = [
                ('Content-Type', 'application/pdf'),
                ('Content-Length', len(pdf_content)),
                ('Content-Disposition', f'attachment; filename="{filename}"')
            ]
            return request.make_response(pdf_content, headers=pdfhttpheaders)
        except Exception as e:
            return request.make_response(f"Error generating PDF: {str(e)}", status=500)

    # These are layout wrappers – we skip them when searching for the document template
    _LAYOUT_CALLS = {
        'web.html_container', 'web.external_layout', 'web.external_layout_standard',
        'web.external_layout_boxed', 'web.external_layout_clean', 'web.external_layout_background',
        'web.basic_layout',
    }

    # Layout templates that must NEVER be overridden via custom XPath inheritance.
    # Modifying these breaks the t-if/t-else/t-elif sibling chains in QWeb compilation.
    _PROTECTED_LAYOUT_KEYS = {
        'web.external_layout_standard',
        'web.external_layout_boxed',
        'web.external_layout_bold',
        'web.external_layout_striped',
        'web.external_layout',
        'web.html_container',
        'web.basic_layout',
        'web.internal_layout',
        'web.address_layout',
    }

    @route('/cyllo_studio/cleanup_broken_layout_views', auth='user', csrf=False, type='json')
    def cleanup_broken_layout_views(self):
        """
        Clean up any Custom_ inherited views that target protected layout templates.
        These cause QWeb SyntaxErrors like 't-elif must be preceded by t-if'.
        Call this to repair the database after such an error occurs.
        """
        removed = []
        try:
            for key in self._PROTECTED_LAYOUT_KEYS:
                base_view = request.env.ref(key, raise_if_not_found=False)
                if not base_view:
                    continue
                custom_views = request.env['ir.ui.view'].sudo().search([
                    ('inherit_id', '=', base_view.id),
                    '|', ('name', 'like', 'Custom_'), ('key', 'like', 'Custom_'),
                ])
                if custom_views:
                    removed.extend(custom_views.mapped('name'))
                    custom_views.unlink()
            return {'success': True, 'removed': removed}
        except Exception as e:
            return {'success': False, 'error': str(e)}

    def _resolve_doc_template(self, template):
        """
        Given a wrapper template name (e.g. ``sale.report_saleorder_zew``), walk its
        ``t-call`` children and return the *first* one that is NOT a known layout
        wrapper.  That is the real document template whose arch we want to edit.

        Returns ``(view_record, resolved_template_name)``.
        If no inner call is found, falls back to the wrapper itself.
        """
        try:
            wrapper_view = request.env.ref(template, raise_if_not_found=False)
            if not wrapper_view:
                wrapper_view = request.env['ir.ui.view'].search([('name', '=', template)], limit=1)
            if not wrapper_view or not wrapper_view.exists():
                return None, template

            arch_src = wrapper_view.arch_base or wrapper_view.arch
            if not arch_src:
                return wrapper_view, template

            try:
                root = etree.fromstring(arch_src.encode('utf-8'))
            except etree.XMLSyntaxError:
                return wrapper_view, template

            # Collect all t-call values in document order, skip layout ones
            for el in root.iter():
                t_call = el.get('t-call')
                if t_call and t_call not in self._LAYOUT_CALLS:
                    # Try to resolve this as an external ID
                    doc_view = request.env.ref(t_call, raise_if_not_found=False)
                    if doc_view and doc_view.exists():
                        return doc_view, t_call

            # Nothing found – return the wrapper itself
            return wrapper_view, template
        except Exception:
            return None, template

    @route('/cyllo_studio/get_report_source', auth='user', csrf=False, type='json')
    def get_report_source(self, template):
        """
        Fetch the raw XML arch of the *document* template (the real content template,
        not the outer wrapper).  Also returns the resolved template name so the
        frontend can pass it back on save.
        """
        try:
            doc_view, doc_template = self._resolve_doc_template(template)

            if not doc_view or not doc_view.exists():
                return {'success': False, 'error': f'Template {template!r} not found'}

            # Always return the base view's full combined architecture so the source editor
            # shows the complete document XML (the Architecture tab content), including
            # any Studio-injected fields from inherited views.
            combined_arch = doc_view._get_combined_arch().xpath('//t[@t-name]')[0]
            arch_xml = etree.tostring(combined_arch, encoding='unicode', pretty_print=True)
            return {'success': True, 'arch': arch_xml, 'doc_template': doc_template}
        except Exception as e:
            return {'success': False, 'error': str(e)}

    @route('/cyllo_studio/save_report_source', auth='user', csrf=False, type='json')
    def save_report_source(self, template, arch, doc_template=None):
        """
        Save the raw XML arch directly to the document template's inherited view
        (or create one).  ``doc_template`` is the resolved document template name
        returned by ``get_report_source``; if not supplied we fall back to
        auto-detecting it again.
        """
        try:
            # Resolve which template to actually save to
            save_template = doc_template or template
            if not doc_template:
                _, save_template = self._resolve_doc_template(template)

            # Validate XML before saving
            try:
                etree.fromstring(arch.encode('utf-8'))
            except etree.XMLSyntaxError as xml_err:
                return {'success': False, 'error': f'Invalid XML: {xml_err}'}

            # Write directly to the base document view so the PDF immediately
            # reflects the changes (no extra inherited view is created).
            base_view = request.env.ref(save_template, raise_if_not_found=False)
            if not base_view or not base_view.exists():
                # Fall back: search by name
                base_view = request.env['ir.ui.view'].search(
                    [('name', '=', save_template)], limit=1)
            if not base_view or not base_view.exists():
                return {'success': False, 'error': f'View {save_template!r} not found'}

            base_view.write({'arch_base': arch})

            # ── FLATTEN INHERITANCE ──────────────────────────────────────────
            # Delete any 'Custom_' inherited views for this template. Since we
            # just saved the full combined arch back to the base 'arch_base',
            # these inherited views are now redundant and their xpaths might
            # point to elements we just deleted/modified/commented out.
            custom_views = request.env['ir.ui.view'].search([
                ('inherit_id', '=', base_view.id),
                ('name', '=', f'Custom_{save_template}'),
            ])
            if custom_views:
                custom_views.sudo().unlink()

            return {'success': True}
        except Exception as e:
            return {'success': False, 'error': str(e)}

    @route('/cyllo_studio/reset_report_source', auth='user', csrf=False, type='json')
    def reset_report_source(self, template, include_header_footer=False):
        """
        Reset the document template's arch back to its factory / module defaults
        by calling ir.ui.view.reset_arch(mode='hard').
        """
        try:
            doc_view, doc_template = self._resolve_doc_template(template)
            if not doc_view or not doc_view.exists():
                return {'success': False, 'error': f'View {template!r} not found'}

            if doc_view.key and doc_view.key.startswith('cyllo_studio_custom.'):
                # This is a custom report created by Cyllo Studio. It has no arch_fs, so reset_arch does nothing.
                # We manually restore the blank skeleton.
                model_name = request.env['ir.model'].sudo().search([('model', '=', doc_view.model)], limit=1).name or doc_view.model
                blank_arch = f"""
            <t t-name="{doc_view.key}">
                <t t-call="web.html_container">
                    <t t-call="web.external_layout">
                        <t t-foreach="docs" t-as="doc">
                            <div class="page">
                                <div class="oe_structure"/>
                                <div class="row">
                                    <div class="col-12">
                                        <h2 class="text-center mt-4">
                                            <span t-esc="doc.name or doc.display_name or ''"/>
                                        </h2>
                                        <p class="text-muted text-center">New Report for {model_name}</p>
                                    </div>
                                </div>
                                <div class="oe_structure"/>
                            </div>
                        </t>
                    </t>
                </t>
            </t>"""
                doc_view.sudo().write({'arch_base': blank_arch})
            else:
                # Hard-reset: restores arch from the module XML file on disk
                doc_view.sudo().reset_arch(mode='hard')

            # Unconditionally delete any custom inherited views on top of the doc template or its children
            custom_views = request.env['ir.ui.view'].search([
                ('inherit_id', 'child_of', doc_view.id),
                '|', ('name', 'like', 'Custom_'), ('key', 'like', 'Custom_'),
            ])
            if custom_views:
                custom_views.sudo().unlink()

            if include_header_footer:
                # Also reset the outer wrapper if it has an arch_fs
                wrapper_view = request.env.ref(template, raise_if_not_found=False)
                if wrapper_view and wrapper_view.exists():
                    if wrapper_view.arch_fs:
                        wrapper_view.sudo().reset_arch(mode='hard')

                    wrapper_custom_views = request.env['ir.ui.view'].search([
                        ('inherit_id', 'child_of', wrapper_view.id),
                        '|', ('name', 'like', 'Custom_'), ('key', 'like', 'Custom_'),
                    ])
                    if wrapper_custom_views:
                        wrapper_custom_views.sudo().unlink()

            fresh_arch = doc_view.arch_base
            return {'success': True, 'arch': fresh_arch}
        except Exception as e:
            return {'success': False, 'error': str(e)}