# -*- coding: utf-8 -*-
from odoo.tests.common import TransactionCase

class TestApprovalTrigger(TransactionCase):

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.env = cls.env(context=dict(cls.env.context, tracking_disable=True))
        
        # Ensure cyllo_approval module is considered installed
        module = cls.env['ir.module.module'].search([('name', '=', 'cyllo_approval')])
        if module:
            module.state = 'installed'
            
        cls.model_id = cls.env['ir.model'].search([('model', '=', 'res.partner')], limit=1)
        
        cls.user = cls.env.user
        cls.company = cls.env.company

    def test_approval_rule_auto_created_and_updated(self):
        """Test that Approval Rule is auto-created on save and updated on update"""
        # Create automation with Approval Trigger
        automation = self.env['work.auto'].create({
            'name': 'Test Approval Sync',
            'model_id': self.model_id.id,
        })
        
        # Simulate node struct
        node = self.env['node.struct'].create({
            'work_auto_id': automation.id,
            'name': 'Approval',
            'trigger_type': 'approval',
            'label': 'Manager Approval',
            'model_id': self.model_id.id,
        })
        
        # Trigger the sync by calling save_data (or simulating what save_data does)
        # Note: save_data is usually called with data payload, but we can call it to test sync
        automation.save_data(None, 'Test Approval Sync', 'approval')
        
        # Check rule creation
        rule = self.env['approval.rule'].search([('name', '=', 'Manager Approval')], limit=1)
        self.assertTrue(rule, "Approval Rule should be auto-created")
        self.assertEqual(rule.model_id.id, self.model_id.id, "Should inherit model")
        
        # Update node
        node.write({'label': 'Director Approval'})
        automation.save_data(None, 'Test Approval Sync', 'approval')
        
        # Check rule update
        self.assertEqual(rule.name, 'Director Approval', "Approval Rule should be updated")

    def test_approved_event_triggers_approved_port(self):
        """Test that APPROVED event routes execution down the Approved branch"""
        # Mocking the Python code generated by the builder
        code = '''
if trigger_type == 'approval':
    if _approval_outcome in ('approved',):
        env.context['test_output'].append('approved_executed')
    elif _approval_outcome in ('rejected',):
        env.context['test_output'].append('rejected_executed')
    elif _approval_outcome in ('expired', 'timeout'):
        env.context['test_output'].append('timeout_executed')
'''
        automation = self.env['work.auto'].create({
            'name': 'Test Approved Port',
            'model_id': self.model_id.id,
            'code': code,
        })
        
        partner = self.env['res.partner'].create({'name': 'Test Partner'})
        output_list = []
        
        # Simulate cyllo_approval calling _process
        automation.with_context(test_output=output_list)._process({
            'records': partner,
            'trigger_type': 'approval',
            'approval_status': 'approved'
        })
        
        self.assertIn('approved_executed', output_list)
        self.assertNotIn('rejected_executed', output_list)
        self.assertNotIn('timeout_executed', output_list)

    def test_rejected_event_triggers_rejected_port(self):
        """Test that REJECTED event routes execution down the Rejected branch"""
        code = '''
if trigger_type == 'approval':
    if _approval_outcome in ('approved',):
        env.context['test_output'].append('approved_executed')
    elif _approval_outcome in ('rejected',):
        env.context['test_output'].append('rejected_executed')
    elif _approval_outcome in ('expired', 'timeout'):
        env.context['test_output'].append('timeout_executed')
'''
        automation = self.env['work.auto'].create({
            'name': 'Test Rejected Port',
            'model_id': self.model_id.id,
            'code': code,
        })
        
        partner = self.env['res.partner'].create({'name': 'Test Partner'})
        output_list = []
        
        automation.with_context(test_output=output_list)._process({
            'records': partner,
            'trigger_type': 'approval',
            'approval_status': 'rejected'
        })
        
        self.assertIn('rejected_executed', output_list)
        self.assertNotIn('approved_executed', output_list)
        self.assertNotIn('timeout_executed', output_list)

    def test_timeout_event_triggers_timeout_port(self):
        """Test that TIMEOUT event routes execution down the Timeout branch"""
        code = '''
if trigger_type == 'approval':
    if _approval_outcome in ('approved',):
        env.context['test_output'].append('approved_executed')
    elif _approval_outcome in ('rejected',):
        env.context['test_output'].append('rejected_executed')
    elif _approval_outcome in ('expired', 'timeout'):
        env.context['test_output'].append('timeout_executed')
'''
        automation = self.env['work.auto'].create({
            'name': 'Test Timeout Port',
            'model_id': self.model_id.id,
            'code': code,
        })
        
        partner = self.env['res.partner'].create({'name': 'Test Partner'})
        output_list = []
        
        automation.with_context(test_output=output_list)._process({
            'records': partner,
            'trigger_type': 'approval',
            'approval_status': 'timeout'
        })
        
        self.assertIn('timeout_executed', output_list)
        self.assertNotIn('approved_executed', output_list)
        self.assertNotIn('rejected_executed', output_list)

    def test_no_duplicate_execution(self):
        """Ensure ports are mutually exclusive and no duplicate execution happens"""
        code = '''
if trigger_type == 'approval':
    if _approval_outcome in ('approved',):
        env.context['test_output'].append('approved_executed')
    elif _approval_outcome in ('rejected',):
        env.context['test_output'].append('rejected_executed')
    elif _approval_outcome in ('expired', 'timeout'):
        env.context['test_output'].append('timeout_executed')
'''
        automation = self.env['work.auto'].create({
            'name': 'Test Mutual Exclusivity',
            'model_id': self.model_id.id,
            'code': code,
        })
        
        partner = self.env['res.partner'].create({'name': 'Test Partner'})
        output_list = []
        
        automation.with_context(test_output=output_list)._process({
            'records': partner,
            'trigger_type': 'approval',
            'approval_status': 'approved'
        })
        
        self.assertEqual(len(output_list), 1, "Only one branch should execute")

