# -*- coding: utf-8 -*-
#############################################################################
#
#    Cyllo Pvt. Ltd.
#
#    Copyright (C) 2025-TODAY Cyllo(<https://www.cyllo.com>)
#    Author: Cyllo(<https://www.cyllo.com>)
#
#    You can modify it under the terms of the GNU LESSER
#    GENERAL PUBLIC LICENSE (LGPL v3), Version 3.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU LESSER GENERAL PUBLIC LICENSE (LGPL v3) for more details.
#
#    You should have received a copy of the GNU LESSER GENERAL PUBLIC LICENSE
#    (LGPL v3) along with this program.
#    If not, see <http://www.gnu.org/licenses/>.
#
#############################################################################
from collections import defaultdict

from odoo import api, fields, models


class AppointmentType(models.Model):
    _inherit = 'appointment.type'

    lead_create = fields.Boolean(
        string='Create Opportunity',
        help='For each confirmed appointment of this type, automatically '
             'create a new CRM opportunity and assign it to the responsible '
             'user (staff member). If the customer already has an active '
             'opportunity with that staff member, the appointment is linked '
             'to the existing one instead.',
    )

    lead_ids = fields.Many2many(
        'crm.lead',
        string='Leads / Opportunities',
        compute='_compute_lead_ids',
        groups='sales_team.group_sale_salesman',
    )
    lead_count = fields.Integer(
        string='Leads Count',
        compute='_compute_lead_ids',
        groups='sales_team.group_sale_salesman',
    )

    @api.depends('appointment_ids', 'appointment_ids.opportunity_id')
    @api.depends_context('allowed_company_ids')
    def _compute_lead_ids(self):
        """Aggregate all CRM leads linked to appointments of each type,
        filtered by the user's allowed companies."""
        allowed_company_ids = [False, *self.env.context.get('allowed_company_ids', [])]
        grouped_data = self.env['appointment.appointment'].sudo()._read_group(
            domain=[
                ('appointment_type_id', 'in', self.ids),
                ('opportunity_id', '!=', False),
                ('opportunity_id.company_id', 'in', allowed_company_ids),
            ],
            groupby=['appointment_type_id'],
            aggregates=['opportunity_id:array_agg'],
        )
        mapped = defaultdict(list)
        for appointment_type, opp_ids in grouped_data:
            mapped[appointment_type.id].extend(opp_ids)
        for appt_type in self:
            opp_ids = mapped.get(appt_type.id, [])
            leads = self.env['crm.lead'].browse(opp_ids)._filter_access_rules('read')
            appt_type.lead_ids = leads
            appt_type.lead_count = len(leads)

    def action_appointment_leads(self):
        """Open the CRM pipeline filtered to leads generated by this type."""
        self.ensure_one()
        action = self.env['ir.actions.act_window']._for_xml_id(
            'crm.crm_lead_opportunities'
        )
        action['domain'] = [('id', 'in', self.lead_ids.ids)]
        action['context'] = dict(default_type='opportunity', create=False)
        return action
