# -*- coding: utf-8 -*-
{
    'name': 'Cyllo Budget Management',
    'version': '1.0.0',
    'category': 'Accounting',
    'summary': """Configure Budget and Debt Management Easily """,
    'description': "We can create Budget , Track the expense and cost according to the given criteria."
                   "Also easily manages the Debt Management System",
    'author': "Cyllo",
    'company': 'Cyllo',
    'maintainer': 'Cyllo',
    'website': 'https://www.cyllo.com',
    'depends': ['cyllo_base', 'account', 'cyllo_base_xlsx'],
    'icon': '/cyllo_budget_management/static/description/budget-management.svg',
    'data': [
        'security/ir_rule.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/ir_cron_data.xml',
        'data/mail_template_data.xml',
        'data/ir_actions_server_data.xml',
        'reports/budget_report_template.xml',
        'reports/debt_report_template.xml',
        'reports/ir_action_report.xml',
        'wizards/debt_payback_wizard.xml',
        'views/analytic_account_views.xml',
        'views/budget_lines_configurator_view.xml',
        'views/budget_budget_view.xml',
        'views/budget_lines_view.xml',
        'views/debt_management.xml',
        'views/budget_management_menu.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
    'post_init_hook': '_post_init_hook',
}
