# -*- coding: utf-8 -*-
#############################################################################
#
#    Cyllo Pvt. Ltd.
#
#    Copyright (C) 2025-TODAY Cyllo(<https://www.cyllo.com>)
#    Author: Cyllo(<https://www.cyllo.com>)
#
#    You can modify it under the terms of the GNU LESSER
#    GENERAL PUBLIC LICENSE (LGPL v3), Version 3.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU LESSER GENERAL PUBLIC LICENSE (LGPL v3) for more details.
#
#    You should have received a copy of the GNU LESSER GENERAL PUBLIC LICENSE
#    (LGPL v3) along with this program.
#    If not, see <http://www.gnu.org/licenses/>.
#
#############################################################################
import requests

from odoo import _, api, fields, models
from odoo.exceptions import ValidationError


class WhatsappMessage(models.Model):
    """Model representing WhatsApp Messages."""
    _name = 'whatsapp.message'
    _description = 'Whatsapp Messages'
    _rec_name = 'message'

    _COMPATIBLE_ATTACHMENT_TYPE = {
        'document': (
            'text/plain', 'application/msword', 'application/vnd.ms-powerpoint',
            'audio/mp3', 'application/pdf',
            'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'application/vnd.openxmlformats-officedocument.presentationml.presentation',
            'application/vnd.ms-excel'),
        'audio': (
            'audio/aac', 'audio/opus', 'audio/mpeg', 'audio/ogg',
            'audio/ogg; codecs=opus', 'audio/amr'),
        'image': ('image/jpeg', 'image/png'),
        'video': ('video/mp4', 'video/3gpp'),
    }

    message = fields.Text(help='Whatsapp message')
    image = fields.Image(help='Choose image here')
    sticker = fields.Image(help='Choose image here')
    video = fields.Binary(help='Choose image here')
    flag = fields.Boolean(help='It checks when author is user')
    attachment_id = fields.Many2one('ir.attachment',
                                    help='Document to be attached')
    message_type = fields.Selection(
        [('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'),
         ('video', 'Video'), ('sticker', 'Sticker'),
         ('document', 'Document')], help='Choose the message template',
        default='text')
    is_voice = fields.Boolean(help='Is voice')
    is_template = fields.Boolean(string='Template',
                                 help='Check this field if message is template')
    template_id = fields.Many2one('whatsapp.template',
                                  string='Whatsapp template',
                                  help='Choose the whatsapp template')
    template_body = fields.Text(string='Template Message',
                                help='The template message to be send.')
    message_uid = fields.Char(string='Message ID',
                              help='The Id generated by whatsapp upon sending')
    company_ids = fields.Many2many('res.company',
                                   default=lambda self: self.env.company,
                                   help='The company responsible for this message')
    state = fields.Selection(
        [('draft', 'Draft'), ('outgoing', 'In Queue'), ('sent', 'Sent'),
         ('delivered', 'Delivered'), ('read', 'Read'), ('received', 'Received'),
         ('error', 'Failed'), ('cancel', 'Cancelled')], default='draft',
        help='The status of message')
    channel_id = fields.Many2one('whatsapp.channel',
                                 help='The channel corresponds to the message')
    is_read = fields.Boolean(string='Seen',
                             help='It checks when the user has seen the message.')
    is_button = fields.Boolean(
        string="Need Button", default=False,
        help="Enable this boolean to add button to the template")
    button_name = fields.Char(
        string="Button Name",
        help="Name of button on template")
    button_url = fields.Char(
        string="Button Url",
        help="Url of button on template")

    def _send_read_receipt(self, message_uid, user_token, phone_uid):
        """
        Send a read receipt to WhatsApp for a given message.

        Parameters:
            - message_uid (str): The ID of the message to mark as read.
            - user_token (str): The access token for the WhatsApp API.
            - phone_uid (str): The phone number ID associated with the WhatsApp account.
        """
        url = f"https://graph.facebook.com/v18.0/{phone_uid}/messages"
        headers = {
            'Authorization': f'Bearer {user_token}',
            'Content-Type': 'application/json'
        }
        payload = {
            "messaging_product": "whatsapp",
            "status": "read",
            "message_id": message_uid
        }
        try:
            requests.post(url, json=payload, headers=headers)
        except requests.exceptions.RequestException as e:
            # Log the error but don't stop the flow
            print(f"Failed to send read receipt: {e}")

    @api.model
    def get_chat_history(self, channel, limit):
        """   Retrieve chat history for a given WhatsApp channel.

            This method retrieves the chat history for a specified WhatsApp
            channel by querying the 'whatsapp.message' model. The chat history
            is returned as a list of dictionaries representing message records.

            Parameters:
              - channel (int): ID of the WhatsApp channel for which to
              retrieve the chat history.

            Returns:
              list: List of dictionaries representing chat history message
              records. Each dictionary contains field-value pairs for the
              message record."""
        channel_history = self.env['whatsapp.message'].sudo().search(
            [('channel_id', '=', int(channel))], limit=limit, order="id desc")
        
        # Identify unread messages from the partner (incoming messages)
        partner_message = channel_history.filtered(lambda x: not x.is_read and not x.flag)
        
        if partner_message:
            # Get user credentials from the channel's associated user
            # Assuming all messages in the channel belong to the same user configuration
            # Use the first message's channel user for credentials
            channel_record = self.env['whatsapp.channel'].sudo().browse(int(channel))
            user = channel_record.user_id
            
            if user and user.token and user.phone_uid:
                for rec in partner_message:
                    # Send read receipt to WhatsApp
                    self._send_read_receipt(rec.message_uid, user.token, user.phone_uid)
                    rec.write({'is_read': True, 'state': 'read'})
            else:
                # If no user configuration, just mark as read locally
                for rec in partner_message:
                    rec.write({'is_read': True, 'state': 'read'})

        if channel_history:
            return channel_history.read()[::-1]
        else:
            return []

    def get_payload(self, partner):
        """
        Generate a payload for sending a WhatsApp message.

        Parameters:
            - partner (res.partner): Partner record representing the recipient.

        Returns:
            dict: Payload dictionary containing information for sending a
            WhatsApp message.
                The dictionary includes the 'messaging_product',
                'recipient_type', and 'to' fields.
        """
        payload = {
            "messaging_product": "whatsapp",
            "recipient_type": "individual",
            "to": partner['whatsapp_number'],
        }
        return payload

    @property
    def get_whatsapp_account_details(self):
        """
         Retrieve WhatsApp account details for the current user.
         Raises:
             ValidationError: If any of the required WhatsApp account details
            (cloud token, account UID, phone UID, or app UID) is missing for the
            current user.

         Returns:
             dict: Dictionary containing WhatsApp account details for the
              current user.The dictionary includes 'cloud_token', 'account_uid',
             'phone_uid', and 'app_uid' fields."""
        if not (self.env.user.token and self.env.user.account_uid and
                self.env.user.phone_uid and self.env.user.app_uid):
            raise ValidationError(
                _('Whatsapp account configuration is required for sending messages. \n '
                  'Go to /Settings/Users & Companies/Users/Whatsapp Account'))
        return {
            'cloud_token': self.env.user.token,
            'account_uid': self.env.user.account_uid,
            'phone_uid': self.env.user.phone_uid,
            'app_uid': self.env.user.app_uid,
        }

    def generate_media_id(self, attachment, token, payload, whatsapp_no):
        """
        Generate a media ID for a WhatsApp media message.

        Parameters:
            - attachment (ir.attachment): The attachment representing the media
            file to be uploaded.
            - token (dict): Dictionary containing the authorization token for
            the request headers.
            - payload (dict): Dictionary containing additional payload data for
             the media upload request.
            - whatsapp_no (str): The WhatsApp number to which the media will be
             associated.

        Raises:
            ValidationError: If the media upload fails, and the response status
             code is not 200.

        Returns:
            str: Media ID associated with the uploaded media file."""

        fname = attachment.store_fname
        file_path = attachment._full_path(fname)
        file_name = attachment.name
        file_type = attachment.mimetype
        files = {"file": (file_name, open(file_path, "rb"), file_type, {})}
        url = f"https://graph.facebook.com/v18.0/{whatsapp_no}/media"
        response = requests.post(url, data=payload, files=files, headers=token)
        whatsapp_media = response.json()
        if response.status_code != 200:
            raise ValidationError(_(whatsapp_media['error']['message']))
        media_id = whatsapp_media.get('id')
        return media_id

    @api.model
    def send_whatsapp_message(self, vals):
        """
          Send a WhatsApp message with optional attachments.

          Parameters:
              - vals (dict): Dictionary containing values for the WhatsApp
              message. It includes 'channel' (WhatsApp channel), 'message'
              (text message), 'attachment' (document attachment), and 'image'
              (image attachment) fields.

          Raises:
              ValidationError: If there is an issue with sending the message,
              and the response status code is not 200.

          Returns:
              dict: Dictionary containing details of the sent WhatsApp message.
             The dictionary includes information such as 'message_uid',
             'state', and other message details."""
        try:
            cloud_token = self.get_whatsapp_account_details['cloud_token']
            phone_uid = self.get_whatsapp_account_details['phone_uid']
            channel = vals['channel']
            channel = self.env['whatsapp.channel'].browse(channel['id'])
            partner = channel.partner_id
            message = vals['message']
            document = vals['attachment']
            image_info = vals['image']
            video_info = vals['video']
            datas = image_info['imageContent'].split(
                ',') if image_info else False
            video_datas = video_info['videoContent'].split(
                ',') if video_info else False
            attachment = self.env['ir.attachment'].browse(
                document[0]) if document else False
            if message or image_info or video_info or document:
                message_values = {
                    'channel_id': channel['id'],
                    'message': message or False,
                    'flag': True,
                    'image': datas[1] if datas else False,
                    'video': video_datas[1] if video_datas else False,
                    'attachment_id': document[0] if document else False
                }
                headers = {'Authorization': f'Bearer {cloud_token}',
                           'Content-Type': 'application/json'}
                payload = self.get_payload(partner)
                token = {'Authorization': f'Bearer {cloud_token}'}
                if image_info:
                    file_name = image_info['file_name'] or False
                    image_type = image_info['file_type'] or False
                    supported_image_types = self._COMPATIBLE_ATTACHMENT_TYPE[
                        'image']
                    if image_type not in supported_image_types:
                        raise ValidationError(
                            _("Attachment mimetype '%s' is not supported by WhatsApp.\n "
                              "Whatsapp supported documents are %s.",
                              image_type,
                              supported_image_types))
                    attachment_record = self.env['ir.attachment'].create({
                        'name': file_name,
                        'mimetype': image_type,
                        'datas': datas[1] if datas else False,
                    })
                    message_values[
                        'attachment_id'] = attachment_record.id if attachment_record else False
                    message_values['message_type'] = 'image'
                    media_id = self.generate_media_id(attachment_record, token,
                                                      payload, phone_uid) \
                        if attachment_record else False
                    if media_id:
                        payload['type'] = 'image'
                        payload['image'] = {'id': media_id, 'caption': message}
                elif video_info:
                    file_name = video_info['file_name'] or False
                    video_type = video_info['file_type'] or False
                    supported_video_types = self._COMPATIBLE_ATTACHMENT_TYPE[
                        'video']
                    if video_type not in supported_video_types:
                        raise ValidationError(
                            _("Attachment mimetype '%s' is not supported by WhatsApp.\n "
                              "Whatsapp supported documents are %s.",
                              video_type,
                              supported_video_types))
                    attachment_record = self.env['ir.attachment'].create({
                        'name': file_name,
                        'mimetype': video_type,
                        'datas': video_datas[1] if video_datas else False,
                    })
                    message_values[
                        'attachment_id'] = attachment_record.id if attachment_record else False
                    message_values['message_type'] = 'video'

                    media_id = self.generate_media_id(attachment_record, token,
                                                      payload, phone_uid) \
                        if attachment_record else False
                    if media_id:
                        payload['type'] = 'video'
                        payload['video'] = {'id': media_id, 'caption': message}
                elif document:
                    supported_document_types = [value for group_values in
                                                self._COMPATIBLE_ATTACHMENT_TYPE.values()
                                                for value in group_values]
                    if attachment.mimetype not in supported_document_types:
                        raise ValidationError(
                            _("Attachment mimetype '%s' is not supported by WhatsApp.",
                              attachment.mimetype))
                    media_id = self.generate_media_id(attachment, token,
                                                      payload,
                                                      phone_uid) if attachment else False
                    if attachment.mimetype.startswith("audio/"):
                        message_values['message_type'] = 'audio'
                        if media_id:
                            payload['type'] = 'audio'
                            payload['audio'] = {
                                'id': media_id,
                            }
                            message_values['is_voice'] = False
                            try:
                                if attachment.mimetype == 'audio/ogg; codecs=opus':
                                    payload['audio']['voice'] = True
                                    message_values['is_voice'] = True
                            except Exception as e:
                                payload['audio']['voice'] = False
                                message_values['is_voice'] = False
                    else:
                        message_values['message_type'] = 'document'
                        if media_id:
                            payload['type'] = 'document'
                            payload['document'] = {'id': media_id,
                                                   'filename': attachment.name}
                else:
                    payload['type'] = 'text'
                    payload['text'] = {'body': message}
                    message_values['message_type'] = 'text'
                whatsapp_response = requests.post(
                    f"https://graph.facebook.com/v17.0/{phone_uid}/messages",
                    json=payload, headers=headers)
                if whatsapp_response.status_code == 200:
                    message_uid = whatsapp_response.json()['messages'][0]['id']
                    message_values['message_uid'] = message_uid
                    message_values['state'] = 'sent'
                    current_message = self.create(message_values)
                    channel.write({
                        'last_message': current_message.message,
                        'last_messenger': "You",
                    })
                    msg = {
                        "channel": channel,
                        "message": current_message.read(),
                    }
                else:
                    raise ValidationError(
                        _(f"Message sending is Failed.\n {whatsapp_response.json()['error']['message']}"))
                return current_message.read()
        except requests.exceptions.ConnectionError:
            return {
                'error': 'ConnectionError',
            }
