# -*- coding: utf-8 -*-
#############################################################################
#
#    Cyllo Pvt. Ltd.
#
#    Copyright (C) 2025-TODAY Cyllo(<https://www.cyllo.com>)
#    Author: Cyllo(<https://www.cyllo.com>)
#
#    You can modify it under the terms of the GNU LESSER
#    GENERAL PUBLIC LICENSE (LGPL v3), Version 3.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU LESSER GENERAL PUBLIC LICENSE (LGPL v3) for more details.
#
#    You should have received a copy of the GNU LESSER GENERAL PUBLIC LICENSE
#    (LGPL v3) along with this program.
#    If not, see <http://www.gnu.org/licenses/>.
#
#############################################################################
import math
import re

import requests
from markupsafe import Markup

from odoo import _, api, fields, models
from odoo.exceptions import UserError, ValidationError
from odoo.tools import plaintext2html


class WhatsappTemplate(models.Model):
    """ Templates for whatsapp """
    _name = 'whatsapp.template'
    _description = 'Whatsapp Template Sending'
    _inherit = ['mail.thread', 'mail.activity.mixin']

    _sql_constraints = [
        ('unique_template_name', 'unique(template_name)',
         "Duplicate template is not allowed for one Meta account."),
    ]

    name = fields.Char(help='Whatsapp template name by user', required=True)
    active = fields.Boolean(default=True,
                            help='The field describes the record is active or not')
    template_name = fields.Char(
        help='The actual name of whatsapp template generated based on whatsapp guidelines',
        compute='_compute_template_name',copy=False)
    user_id = fields.Many2one('res.users', default=lambda self: self.env.user,
                              help='The user is responsible for this message')
    model_id = fields.Many2one('ir.model', string='Reference Model',
                               required=True, ondelete='cascade',
                               help='The model the template is bound.')
    binary_field_path = fields.Char("Path of binary field",
                                    help="Specify the path of field which will contain data for image")
    lang_id = fields.Many2one("res.lang", "Language",
                              default=lambda self: self.env[
                                  "res.lang"].search(
                                  [("code", "=", self.env.user.lang)], limit=1))
    template_uid = fields.Char(string='Template ID', readonly=True,
                               help='Id generated by whatsapp',copy=False)
    state = fields.Selection(
        [('draft', 'Draft'), ('pending', 'Pending'), ('in_appeal', 'In Appeal'),
         ('approved', 'Approved'), ('paused', 'Paused'),
         ('disabled', 'Disabled'),
         ('rejected', 'Rejected'), ('pending_deletion', 'Pending Deletion'),
         ('deleted', 'Deleted'), ('limit_exceeded', 'Limit Exceeded')],
        default='draft',
        string='Status', help=""" *The status of whatsapp template
                             *  Pending : Indicates that the template is still under review by WhatsApp. Review can 
                             take up to 24 hours.
                             * Approved : The template was approved by WhatsApp and can be used to notify customers.
                             * Rejected : The template has been rejected by WhatsApp during the review process.""")
    category = fields.Selection(
        [('utility', 'Utility'), ('marketing', 'Marketing'),
         ('authentication', 'Authentication')], default='marketing',
        help=""" * The template category.
                                *  Utility: Send account updates, order updates, alerts, and more to share.
                                * Marketing: Promote your products, services or business.
                                * Authentication: Send codes that allow your customers to access their accounts.""")
    header_type = fields.Selection(
        [('none', 'None'), ('text', 'Text'), ('document', 'Document'),
         ('image', 'Image')], default='none',
        help='Choose the header type here',
        required=True)
    attachment_ids = fields.Many2many('ir.attachment',
                                      string="Header Static template",
                                      copy=False,
                                      help='The sample document for static header used for whatsapp verification')
    report_id = fields.Many2one('ir.actions.report', string="Document",
                                domain="[('model_id', '=', model_id)]",
                                help='The document for static header used in whatsapp template')
    header_text = fields.Char(string='Template Header Text',
                              help='Enter the header text', size=60)
    footer_text = fields.Char(string='Template Footer Text',
                              help='Enter the footer text here')
    body = fields.Text(string='Template Body', required=True,
                       help="""* Enter the body of template:
                       * Use {{number}} for variable place holder, eg: {{1}}.
                       * Use *{{1}}* for bold the variable.
                       * Use _{{1}}_ for italic variable.
                       * Use ~{{1}}~ for striking variable.
                       * Use ```{{1}}``` for Monospace code """)
    variable_ids = fields.One2many('template.variable', 'template_id',
                                   string='Variables',
                                   help='The variables defined for whatsapp template body',
                                   readonly=False,
                                   compute='_compute_variable_ids', store=True)
    reason = fields.Text(help='The reason for rejection')
    is_reason_update = fields.Boolean(string='Reason Updates',
                                      help='The reason for rejection from the webhook response')
    quality = fields.Selection(
        [('none', 'None'), ('red', 'Red'), ('yellow', 'Yellow'),
         ('green', 'Green')],
        default='none', help='The quality scored by the template', copy=False,
        tracking=True)
    company_ids = fields.Many2many('res.company',
                                   help='The company responsible for this message')
    is_button = fields.Boolean(
        string="Need Button", default=False,
        help="Enable this boolean to add button to the template")
    button_name = fields.Char(
        string="Button Name",
        help="Name of button on template")
    button_url = fields.Char(
        string="Button Url",
        help="Url of button on template")

    @api.constrains('attachment_ids', 'header_type')
    def _check_attachment_ids(self):
        """
          Check constraints on attachment_ids and header_type.

          This method ensures that the attachments used as headers adhere to the constraints:
          1. For header types 'image' or 'document', only one attachment is allowed per template.
          2. The attached file types must be supported for the given header type.

          Raises:
              ValidationError: If the constraints are violated.

          Returns:
              None
        """
        for record in self:
            if record.header_type in ['image', 'document']:
                if len(record.attachment_ids) > 1:
                    record.attachment_ids = [record.attachment_ids.ids[0]]
                    raise ValidationError(
                        _('You can only use one header attachment for '
                          'each template'))
                supported_mimetypes = self.env[
                    'whatsapp.message']._COMPATIBLE_ATTACHMENT_TYPE.values()
                supported_type = [item for category_values in
                                  supported_mimetypes for item in
                                  category_values]
                unsupported_types = record.attachment_ids.filtered(
                    lambda att: att.mimetype and att.mimetype
                                not in supported_type)
                if unsupported_types:
                    file_types = unsupported_types.mapped('mimetype')
                    raise ValidationError(
                        _("The %(file_type)s file type is not supported for header type %(header_type)s",
                          file_type=file_types, header_type=record.header_type))

    @api.depends('header_text', 'body')
    def _compute_variable_ids(self):
        """
           Compute variable IDs based on header_text and body content.

           The computed variable IDs are stored in the 'variable_ids' field of
           the template.

           Returns: None """
        for record in self:
            pattern = r'{{(.*?)}}'
            record.variable_ids = False
            if record.header_type == 'text':
                header_variable = re.search(pattern, record.header_text) if (
                    record.header_text) else None
                if header_variable:
                    record.variable_ids = [fields.Command.create({
                        'display_name': 'header',
                        'type': 'header',
                        'sample_value': 'Sample Value',
                        'variable_value': 'name'
                    })]
            body_variable = re.search(pattern,
                                      record.body) if record.body else None
            body_variable_collection = re.findall(pattern,
                                                  record.body) if body_variable else None
            if body_variable_collection:
                record.variable_ids = [fields.Command.create({
                    'display_name': 'body- {' + rec + '}',
                    'type': 'body',
                    'template_id': record.id,
                    'sample_value': 'Sample Value',
                    'variable_value': 'name'
                }) for rec in body_variable_collection]

    @api.constrains('header_text')
    def _check_header_text(self):
        """
          Check constraints related to header text in WhatsApp templates.

          Raises:
              ValidationError: If the number of variables in the header text is
              greater than one.

          Returns:
              None
          """
        if self.header_type == 'text':
            pattern = r'{{(.*?)}}'
            pattern_present = re.search(pattern,
                                        self.header_text) if self.header_text else False
            matches = re.findall(pattern,
                                 self.header_text) if pattern_present else 0
            variable_count = len(matches) if matches else 0
            if variable_count > 1:
                raise ValidationError(
                    _('Only one variable allowed for header text'))

    @api.depends('name')
    def _compute_template_name(self):
        """
        Compute the template name based on the 'name' field.

        Returns:
            None
        """
        for record in self:
            db_uuid = self.env['ir.config_parameter'].sudo().get_param(
                'database.uuid')
            db_uuid_formatted = db_uuid.replace('-', '')
            template_name = str(record.name).replace(" ", "_")
            record.template_name = f"{template_name}_{db_uuid_formatted}"

    @property
    def get_whatsapp_account_details(self):
        """
        Retrieve WhatsApp account details for the current user.

        Returns:
            dict: Dictionary containing WhatsApp account details for the current
             user. The dictionary includes 'cloud_token', 'account_uid',
            'phone_uid', and 'app_uid' fields.

        Raises:
            ValidationError: If any of the required WhatsApp account details
            (cloud token, account UID, phone UID, or app UID) is missing for
            the current user.
        """
        if not (self.env.user.token and self.env.user.account_uid and
                self.env.user.phone_uid and self.env.user.app_uid):
            raise ValidationError(
                _('Whatsapp account configuration is required for sending messages. \n '
                  'Go to /Settings/Users & Companies/Users/Whatsapp Account'))
        return {
            'cloud_token': self.env.user.token,
            'account_uid': self.env.user.account_uid,
            'phone_uid': self.env.user.phone_uid,
            'app_uid': self.env.user.app_uid,
        }

    @api.ondelete(at_uninstall=False)
    def _unlink_if_delete_or_draft(self):
        """Override the unlink method to prevent deletion of whatsapp template.
            This method is used to prevent the deletion of template that are
            not in the 'draft' or 'deleted' states.
            @raises: UserError if any template being unlinked is not in 'draft'
            or 'deleted' state.
            @return: None """
        if any(template.state not in ('draft', 'deleted', 'rejected') for
               template in self):
            raise UserError(
                _('You cannot delete a whatsapp template which is not draft, rejected ,or deleted!'))

    # Template creation
    def _get_header_handle(self):
        """ Get the header handle for the template."""
        if not self.attachment_ids:
            raise UserError(_('Please select sample document for template'))
        if self.attachment_ids:
            cloud_token = self.get_whatsapp_account_details['cloud_token']
            app_uid = self.get_whatsapp_account_details['app_uid']
            url = f'https://graph.facebook.com/v18.0/{app_uid}/uploads'
            for record in self.attachment_ids:
                base = int(
                    math.floor(math.log(self.attachment_ids.file_size, 1024)))
                file_length = round(
                    self.attachment_ids.file_size / (1024 ** base))
                params = {
                    'file_length': file_length,
                    'file_type': record.mimetype,
                    'access_token': cloud_token
                }
                if self.header_type == 'document' and record.mimetype != 'application/pdf':
                    raise ValidationError(
                        _('Only pdf type documents are supported for media template'))
                if self.header_type == 'image' and record.mimetype not in [
                    'image/png', 'image/jpeg']:
                    raise ValidationError(
                        _('Only png or jpeg types are supported for image type media template'))
            response = requests.post(url, params=params)
            if response.status_code != 200:
                raise ValidationError(_('Uploading the sample document failed'))
            upload_session_id = response.json().get('id')
            # Initiate Upload
            url = f"https://graph.facebook.com/v18.0/{upload_session_id}"
            headers = {"Authorization": f"OAuth {cloud_token}",
                       "file_offset": "0"}
            for attachment in self.attachment_ids:
                fname = attachment.store_fname
                file_path = attachment._full_path(fname)
                file_name = attachment.name
                file_type = attachment.mimetype
                files = {
                    "file": (file_name, open(file_path, "rb"), file_type, {})}
            response = requests.post(url, headers=headers, data=files)
            if response.status_code == 200:
                return response.json().get('h')
            else:
                raise ValidationError(_('Uploading the sample document failed'))

    def _create_header_components(self):
        """ Create header components for the template."""
        header = {"type": "HEADER", "format": self.header_type}
        if self.header_type == 'text':
            header["text"] = self.header_text
            header_sample = self.variable_ids.search(
                [('display_name', '=', 'header'),
                 ('template_id', '=', self.id)])
            if header_sample:
                header["example"] = {
                    "header_text": [header_sample.sample_value]}
        elif self.header_type in ['document', 'image']:
            header_handle = self._get_header_handle()
            header["example"] = {"header_handle": [header_handle]}
        return header

    def _create_body_components(self):
        """ Create body components for the template."""
        body = {"type": "BODY", "text": self.body}
        body_sample = self.variable_ids.search(
            [('display_name', 'ilike', 'body'),
             ('template_id', '=', self.id)]).mapped('sample_value')
        if body_sample:
            body["example"] = {"body_text": [body_sample]}
        return body

    def action_create_template(self):
        """ Create a WhatsApp template."""
        if self.header_type == 'image':
            if not self.binary_field_path:
                raise ValidationError(_('Please provide image file path'))
            parts = self.binary_field_path.split('.')
            model = self.model_id.id
            flag = 0
            for part in parts:
                flag += 1
                if model:
                    field = self.env['ir.model.fields'].sudo().search(
                        [('name', '=', part), ('model_id', '=', model)])
                    if field:
                        if flag != len(parts):
                            if field.ttype == 'many2one':
                                model = self.env['ir.model'].sudo().search(
                                    [('model', '=', field.relation)]).id
                            else:
                                model = False
                        else:
                            if field.ttype != 'binary':
                                return {
                                    'type': 'ir.actions.client',
                                    'tag': 'display_notification',
                                    'params': {
                                        'message': _(
                                            'The last field must be binary'),
                                        'type': 'warning',
                                    },
                                }
                else:
                    return {
                        'type': 'ir.actions.client',
                        'tag': 'display_notification',
                        'params': {
                            'message': _('Wrong path'),
                            'type': 'warning',
                        },
                    }
        cloud_token = self.get_whatsapp_account_details['cloud_token']
        account_uid = self.get_whatsapp_account_details['account_uid']
        headers = {'Authorization': f'Bearer {cloud_token}',
                   'Content-Type': 'application/json'}
        components = []
        if self.header_type != 'none':
            components.append(self._create_header_components())
        if self.body:
            components.append(self._create_body_components())
        if self.footer_text:
            footer = {"type": "FOOTER", "text": self.footer_text}
            components.append(footer)
        if self.is_button:
            cta = {
                "type": "BUTTONS",
                "buttons": [
                    {
                        "type": "url",
                        "url": self.button_url,
                        "text": self.button_name
                    },
                ]
            }
            components.append(cta)
        payload = {
            "name": self.template_name,
            "language": self.lang_id.code,
            "category": self.category,
            "components": components
        }
        response = requests.post(
            f"https://graph.facebook.com/v18.0/{account_uid}/message_templates",
            json=payload, headers=headers)
        if response.status_code != 200:
            error = response.json()['error']
            raise ValidationError(
                _('%s\n%s\n%s', error['message'], error['error_user_title'],
                  error['error_user_msg']))
        template_response = response.json()
        self.template_uid = template_response.get('id')
        if template_response.get('status'):
            if template_response.get('status') == 'REJECTED':
                self.is_reason_update = True
                self.reason = "Template format is not correct, please check."
            self.state = template_response.get('status').lower()

    # Template validation
    def action_get_template(self):
        """ Get the WhatsApp template."""
        cloud_token = self.get_whatsapp_account_details['cloud_token']
        account_uid = self.get_whatsapp_account_details['account_uid']
        url = f"https://graph.facebook.com/v17.0/{account_uid}/message_templates?name={self.template_name}"
        header = {'Authorization': f'Bearer {cloud_token}'}
        response = requests.get(url, headers=header)
        response_data = response.json()['data'][0]
        template_status = response_data['status']
        self.state = template_status.lower()

    # Sending template
    def _get_header_component(self, record, attachment, partner):
        """Get header components for sending a template."""
        header = {"type": "header"}
        cloud_token = self.get_whatsapp_account_details['cloud_token']
        phone_uid = self.get_whatsapp_account_details['phone_uid']
        payload = {
            "messaging_product": "whatsapp",
            "recipient_type": "individual",
            "to": partner.whatsapp_number
        }
        token = {'Authorization': f'Bearer {cloud_token}'}
        if self.header_type == 'text':
            header_variables = self.variable_ids.filtered(
                lambda line: line.display_name == 'header')
            if header_variables:
                variable_value = self._extract_variable_value(header_variables,
                                                              record)
                header["parameters"] = [
                    {"type": "text", "text": variable_value[0]}]
        if self.header_type == 'document':
            media_id = self.env['whatsapp.message'].generate_media_id(
                attachment, token, payload,
                phone_uid) if self.report_id else False
            if not media_id:
                raise ValidationError(_('Media ID is not generated.'))
            header["parameters"] = [{"type": "document",
                                     "document": {'id': media_id,
                                                  'filename': attachment.name}}]
        if self.header_type == 'image':
            current_value = record
            for attribute_name in self.binary_field_path.split('.'):
                if hasattr(current_value, attribute_name):
                    current_value = getattr(current_value, attribute_name)
                else:
                    current_value = None
                    break
            attachment_values = {
                'name': 'Partner Image',
                'type': 'binary',
                'datas': current_value or '',
                'res_model': self.model_id.model,
                'res_id': self.id,  # The ID of the record to associate with
            }
            attachment = self.env['ir.attachment'].create(attachment_values)
            if not attachment.store_fname:
                raise ValidationError(
                    _(f"This model Does not contain Attachment in {self.binary_field_path} field "))
            media_id = self.env['whatsapp.message'].generate_media_id(
                attachment, token, payload,
                phone_uid) if attachment else False
            header["parameters"] = [
                {"type": "image", "image": {'id': media_id}}]
        header_values = {'header': header, 'attachment': attachment}
        return header_values

    def _get_body_component(self, record):
        """ Get body components for sending a template."""
        body = {"type": "body"}
        body_variables = self.variable_ids.filtered(
            lambda line: line.display_name != 'header')
        if body_variables:
            variable_value = self._extract_variable_value(body_variables,
                                                          record)
            parameters = []
            for val in variable_value:
                parameters += {"type": "text", "text": val},
            body["parameters"] = parameters
        return body

    def action_send_template_marketing(self, record, attachment, partner,
                                       cloud_token, phone_uid):
        """ Send a WhatsApp template."""
        if not record:
            raise ValidationError(_('Record is missed'))
        headers = {
            'Authorization': f'Bearer {cloud_token}',
            'Content-Type': 'application/json', }
        components = []
        if self.header_type != 'none':
            header_values = self._get_header_component_marketing(
                record, attachment, partner, cloud_token, phone_uid)
            components.append(header_values['header'])
        if self.body:
            components.append(self._get_body_component(record))
        if self.is_button:
            cta_button = {
                "type": "button",
                "sub_type": "url",
                "index": "1",
            }
            components.append(cta_button)
        payload = {
            "messaging_product": "whatsapp",
            "recipient_type": "individual",
            "to": partner.whatsapp_number,
            "type": "template",
            "template": {
                'name': self.template_name,
                "language": {
                    "code": self.lang_id.code
                },
                "components": components
            }
        }
        response = requests.post(
            f"https://graph.facebook.com/v17.0/{phone_uid}/messages",
            json=payload, headers=headers)
        if response.status_code == 200:
            template_body = self._get_formatted_template_body(record=1,
                                                              demo_value=False)
            channel = self.env['whatsapp.channel'].search(
                [('sender_id', '=', self.env.user.partner_id.id),
                 ('partner_id', '=', partner.id)])
            message_values = {
                'is_template': True,
                'template_id': self.id,
                'flag': True,
                'message_uid': response.json()['messages'][0]['id'],
                'state': 'sent',
            }
            if self.header_type != 'none':
                message_values['message_type'] = self.header_type
                if self.header_type == 'text':
                    header = self._get_formatted_template_header(
                        record=1, demo_value=False)
                    template_body = header + template_body
                if header_values and header_values['attachment'] != None:
                    attachment = header_values['attachment']
                    message_values['attachment_id'] = attachment.id
                if self.header_type == 'image':
                    message_values['image'] = attachment.datas
            if self.is_button:
                message_values['is_button'] = True
                message_values['button_name'] = self.button_name
                message_values['button_url'] = self.button_url
            if channel:
                message_values['channel_id'] = channel.id
            else:
                channel_record = self.env['whatsapp.channel'].create({
                    'name': partner.name,
                    'partner_id': partner.id,
                    'sender_id': self.env.user.partner_id.id,
                    'user_id': self.env.user.id
                })
                message_values['channel_id'] = channel_record.id
            message_values['template_body'] = template_body
            self.env['whatsapp.message'].create(message_values)
            return message_values['message_uid']
        else:
            error_message = response.json()['error']['message']
            raise ValidationError(
                _(error_message))

    def _get_header_component_marketing(self, record, attachment, partner,
                                        cloud_token, phone_uid):
        """Get header components for sending a template."""
        header = {
            "type": "header",
        }
        payload = {
            "messaging_product": "whatsapp",
            "recipient_type": "individual",
            "to": partner.whatsapp_number
        }
        token = {
            'Authorization': f'Bearer {cloud_token}',
        }
        if self.header_type == 'text':
            header_variables = self.variable_ids.filtered(
                lambda line: line.display_name == 'header')
            if header_variables:
                variable_value = self._extract_variable_value(
                    header_variables, record)
                header["parameters"] = [
                    {"type": "text", "text": variable_value[0]}]
        if self.header_type == 'document':
            media_id = self.env['whatsapp.message'].generate_media_id(
                attachment, token, payload,
                phone_uid) if self.report_id else False
            if not media_id:
                raise ValidationError(_('Media ID is not generated.'))
            header["parameters"] = [{"type": "document",
                                     "document": {'id': media_id,
                                                  'filename': attachment.name}}]
        if self.header_type == 'image':
            current_value = record
            for attribute_name in self.binary_field_path.split('.'):
                if hasattr(current_value, attribute_name):
                    current_value = getattr(current_value, attribute_name)
                else:
                    current_value = None
                    break
            attachment_values = {
                'name': 'Partner Image',
                'type': 'binary',
                'datas': current_value or '',
                'res_model': self.model_id.model,
                'res_id': self.id,
            }
            attachment = self.env['ir.attachment'].create(attachment_values)
            media_id = self.env['whatsapp.message'].generate_media_id(
                attachment,
                token,
                payload,
                phone_uid) if attachment else False
            header["parameters"] = [{
                "type": "image",
                "image": {
                    'id': media_id,
                }
            }]
        header_values = {
            'header': header,
            'attachment': attachment
        }
        return header_values

    def action_send_template(self, record, attachment, partner):
        """ Send a WhatsApp template."""
        if not record:
            raise ValidationError(_('Record is missed'))
        cloud_token = self.get_whatsapp_account_details['cloud_token']
        phone_uid = self.get_whatsapp_account_details['phone_uid']
        headers = {'Authorization': f'Bearer {cloud_token}',
                   'Content-Type': 'application/json'}
        components = []
        if self.header_type != 'none':
            header_values = self._get_header_component(record, attachment,
                                                       partner)
            components.append(header_values['header'])
        if self.body:
            components.append(self._get_body_component(record))
        payload = {
            "messaging_product": "whatsapp",
            "recipient_type": "individual",
            "to": partner.whatsapp_number,
            "type": "template",
            "template": {
                'name': self.template_name,
                "language": {"code": self.lang_id.code},
                "components": components
            }
        }
        response = requests.post(
            f"https://graph.facebook.com/v17.0/{phone_uid}/messages",
            json=payload, headers=headers)
        if response.status_code == 200:
            template_body = self._get_formatted_template_body(record=1,
                                                              demo_value=False)
            channel = self.env['whatsapp.channel'].search(
                [('sender_id', '=', self.env.user.partner_id.id),
                 ('partner_id', '=', partner.id)])
            message_values = {
                'is_template': True,
                'template_id': self.id,
                'flag': True,
                'message_uid': response.json()['messages'][0]['id'],
                'state': 'sent',
            }
            if self.header_type != 'none':
                message_values['message_type'] = self.header_type
                if self.header_type == 'text':
                    header = self._get_formatted_template_header(record=1,
                                                                 demo_value=False)
                    template_body = header + template_body
                if header_values and header_values['attachment'] is not None:
                    attachment = header_values['attachment']
                    message_values['attachment_id'] = attachment.id
                if self.header_type == 'image':
                    message_values['image'] = attachment.datas
            if channel:
                message_values['channel_id'] = channel.id
            else:
                channel = self.env['whatsapp.channel'].create({
                    'name': partner.name,
                    'partner_id': partner.id,
                    'sender_id': self.env.user.partner_id.id,
                    'user_id': self.env.user.id
                })
                message_values['channel_id'] = channel.id
            message_values['template_body'] = template_body
            msg = self.env['whatsapp.message'].create(message_values)
            channel.write({
                'last_message': msg.message,
                'last_messenger': "You",
            })
        else:
            error_message = response.json()['error']['message']
            raise ValidationError(_(error_message))

    def action_delete_template(self):
        """Delete a WhatsApp template."""
        cloud_token = self.get_whatsapp_account_details['cloud_token']
        account_uid = self.get_whatsapp_account_details['account_uid']
        url = f"https://graph.facebook.com/v17.0/{account_uid}/message_templates?name={self.template_name}"
        header = {'Authorization': f'Bearer {cloud_token}'}
        response = requests.delete(url, headers=header)
        if response.status_code != 200:
            raise ValidationError(
                _(response.json()['error'].get('error_user_title')))
        self.state = 'deleted'


    def action_wa_template_preview(self):
        """ Generate an action for opening a new window to preview a
        WhatsApp template."""
        return {
            "type": "ir.actions.act_window",
            "name": "Template Preview",
            "res_model": "whatsapp.template.preview",
            "views": [[self.env.ref(
                'cyllo_whatsapp.view_whatsapp_template_preview_form').id,
                       "form"]],
            "target": "new",
            "context": {'dialog_size': 'medium', 'default_template_id': self.id}
        }

    # Whatsapp preview
    @api.model
    def _modify_text_to_html(self, text_body):
        """
        Convert WhatsApp formatted text to HTML.
        This function takes a text in WhatsApp format and converts it into HTML format.
        It supports the following formatting styles:
        - Bold: *text*
        - Italics: _text_
        - Strikethrough: ~text~
        - Code: ```text```

        Parameters:
        - body_html (str): The text in WhatsApp format to be converted.

        Returns:
        Markup: The formatted HTML text.
        """
        html_body = str(plaintext2html(text_body))
        formatting_patterns = [(r'\*(.*)\*', '<b>\\1</b>'),
                               (r'~(.*)~', '<s>\\1</s>'),
                               (r'_(.*)_', '<i>\\1</i>'),
                               (r'```(.*)```', '<code>\\1</code>')]
        for pattern, replacement in formatting_patterns:
            html_body = re.sub(pattern, replacement, html_body)
        return Markup(html_body)

    def _extract_variable_value(self, variable_records, attribute):
        """ Extract variable values from the specified attribute."""
        substitute_values = []
        objects = attribute
        for rec in variable_records:
            attribute = objects
            for attr in rec.variable_value.split('.'):
                if not hasattr(attribute, attr):
                    raise ValidationError(
                        f"'{attribute}' object has no attribute '{attr}'")
                attribute = getattr(attribute, attr)
            substitute_values.append(str(attribute))
        return substitute_values

    def _get_formatted_template_body(self, demo_value, record):
        """Get formatted body and header with specified values.
        :param bool demo_value: if true, sample value is taken instead of
        variable value
        :return Markup:
        """
        body = self.body
        body_variable = self.variable_ids.filtered(
            lambda line: line.display_name != 'header')
        if demo_value:
            body_values = body_variable.mapped('sample_value')
        else:
            model = self.model_id.model
            source_record = self.env[model].browse(record)
            body_values = self._extract_variable_value(body_variable,
                                                       source_record)
        for i in range(1, len(body_values) + 1):
            placeholder = "{{" + str(i) + "}}"
            body = body.replace(placeholder, body_values[i - 1])
        return self._modify_text_to_html(f'{body}')

    def _get_formatted_template_header(self, demo_value, record):
        """ Get a formatted template header with specified values."""
        self.ensure_one()
        header = self.header_text
        if self.header_type == 'text' and self.header_text:
            header_variables = self.variable_ids.filtered(
                lambda line: line.display_name == 'header')
            if header_variables:
                if demo_value:
                    header = self.header_text.replace('{{1}}',
                                                      header_variables.sample_value)
                else:
                    model = self.model_id.model
                    source_record = self.env[model].browse(record)
                    model_values = self._extract_variable_value(
                        header_variables, source_record)
                    header = self.header_text.replace('{{1}}', model_values[0])
        formatted_header = str(plaintext2html(header))
        pattern = r"<p>"
        replacement = r"<p><b>"
        formatted_header = re.sub(pattern, replacement, formatted_header,
                                  count=1)
        return Markup(formatted_header)
